default_twitter: &default_twitter
  twitter_api_key: <%= ENV["TWITTER_API_KEY"] %>
  twitter_api_secret: <%= ENV["TWITTER_API_SECRET"] %>

development:
  secret_key_base: b82c3844a7fb7d1611f40c1f012f92f51994b1d22701aaabe5d730f977f88b6a40f80d357e3e37d102ec41c6222cc424d39c5867c25c906be5c5d4001a9a31a9
  <<: *default_twitter

test:
  secret_key_base: 0812bf89e80ad2616664d009c71870b5d262d8c34730c46d88049958bf8d0c2e910f03eb5b144daefbec37275fa7b0fb5441be03dd2889d936ce362c5fb35ab5
  <<: *default_twitter

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  twitter_api_key: <%= ENV["TWITTER_API_KEY"] %>
  twitter_api_secret: <%= ENV["TWITTER_API_SECRET"] %>